[package]
name = "asset_mapper"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
phf_codegen = "0.11.3"
mime_guess = "2.0.5"